# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/StochasticLexemes

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Build test
          command: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run:
          name: Run tests
          command: cat /dev/null | sbt test:test

      - run:
          name: Build Prod
          command: cat /dev/null | sbt compile

      - run:
          name: Create distribution
          command: pwd && ls -l ./project && cat /dev/null | sbt assembly

      - persist_to_workspace:
          root: ./target/scala-2.12/
          paths: stochastic-lexemes-assembly-1.0.jar

      - attach_workspace:
              at: /tmp/workspace

      - run:
          name: Dockerize
          command: |
            docker build -t ciroque/StochasticLexemes:$CIRCLE_BRANCH .
            docker run --name StochasticLexemes ciroque/StochasticLexemes:$CIRCLE_BRANCH
            docker cp /tmp/workspace/stochastic-lexemes-assembly-1.0.jar StochasticLexemes:/opt/StochasticLexemes
            docker stop StochasticLexemes