name: deployer
author: Steve Wagner <ciroque@live.com>
run-name: Deploying Image
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  build:
    uses: ./.github/workflows/builder.yml

  tests:
    uses: ./.github/workflows/tester.yml
    needs: [build]

  assemble:
    uses: ./.github/workflows/assembler.yml
    needs: [tests]

  build-image:
    uses: ./.github/workflows/image-builder.yml
    needs: [assemble]

