name: build-image
run-name: Building Image
on: [workflow_call]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Download fat jar
        uses: actions/download-artifact@v2
        with:
          name: stochastic-lexemes-assembly
          path: target/scala-2.13/stochastic-lexemes-assembly-1.0.1.jar

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ciroque/stochastic-lexemes:${{ github.head_ref || github.ref_name }}
